### PR TITLE
fix(cfapi): requeue after DB error

### LINKED ISSUE #115: Any options for the retry?
Does [origin-ca-issuer](https://github.com/cloudflare/origin-ca-issuer) support any option for the retry to be able to prevent some errors e.g.
```
Failed to sign certificate request: unable to sign request: Cloudflare API Error code=1100 message=Failed to write certificate to Database
```
Is there a way to do this automatically?

### LINKED ISSUE #116: Random certificate missbehavior.
Certs are correctly being issued until i've got the following error:

> The certificate request has failed to complete and will be retried: Failed to sign certificate request: unable to sign request: Cloudflare API Error code=1201 message=CA signing failure. Could not parse returned certificate

To fix this, i must delete all of originIssuer objects and recreate them. Any suggestions what is wrong?

### PR DESCRIPTION
**Pull request by terinjokes**
The Origin CA API occasionally returns error code 1100 signaling a failure to write the certificate to the database. This reconciler intepreted this error as a permament failure, despite no local issues.

This changeset detects this error code and requeues the CertificateRequest with controller-runtime's default backoff behavior.

Fixes: #115
Fixes: #116

### CODE REVIEW

File: pkgs/controllers/certificaterequest.go [hunk 1]
```diff
@@ -135,6 +139,15 @@ func (r *CertificateRequestController) Reconcile(ctx context.Context, cr *certma
 	}
 
 	pem, err := p.Sign(ctx, cr)
+
+	var apiError cfapi.APIError
+	if errors.As(err, &apiError) {
+		if apiError.Code == originDBWriteErrorCode {
+			log.Error(err, "requeue-ing after API error")
+			return reconcile.Result{Requeue: true}, nil
```
Comment (pims) [inline pkgs/controllers/certificaterequest.go]: Should we delay the requeue as to not overwhelm the backend if it’s possibly already having a bad time?

**Review by pims — APPROVED** [review]

File: pkgs/controllers/certificaterequest.go (hunk 1 above)
Comment (terinjokes) [reply pkgs/controllers/certificaterequest.go]: The controller requeues with `workqueue.AddRateLimited`, which is an exponential backoff (and is subject to a workqueue qps limit as well). Providing our own RequeueAfter disables this, and I'm not convinced we'd pick a better value, especially in lieu of failure counts.

Comment (cbroglie) [reply pkgs/controllers/certificaterequest.go]: Just curious, why this form rather than `return reconcile.Result{}, err`?

They're functionally equivalent as far as the backoff, but returning the error has controller-runtime increment its `controller_runtime_reconcile_errors_total` metric, which seems appropriate for this case.

File: pkgs/controllers/certificaterequest.go [hunk 2]
```diff
@@ -135,6 +139,15 @@ func (r *CertificateRequestController) Reconcile(ctx context.Context, cr *certma
 	}
 
 	pem, err := p.Sign(ctx, cr)
+
+	var apiError cfapi.APIError
```
Comment (cbroglie) [inline pkgs/controllers/certificaterequest.go]: Should this be `*cfapi.APIError` b/c the error returned by `Sign` will be a `*cfapi.APIError`? https://github.com/cloudflare/origin-ca-issuer/blob/9cbc0d54b1c5ca7971dabe114b3891478a2e7c90/internal/cfapi/cfapi.go#L120

Comment (cbroglie) [reply pkgs/controllers/certificaterequest.go]: https://goplay.space/#qKH9IobZ_4f

Comment (terinjokes) [reply pkgs/controllers/certificaterequest.go]: I was debating on if `APIError` or `*APIError` should implement the `error` interface, on account that the pointer receiver made this `error.As` check look bad. The original PR had partially switched to `APIError` but missed this one case. I've added more tests to verify the error type, and reverted back to `*APIError` after finding the Go blog posts also use the pointer receiver.

**Review by cbroglie — APPROVED** [review]
